# Generated by Django 4.0.5 on 2022-07-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_experience_slug_remove_projects_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutMe',
        ),
        migrations.AlterField(
            model_name='experience',
            name='image',
            field=models.ImageField(upload_to='files/website'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(upload_to='files/website'),
        ),
    ]
