# Generated by Django 4.0.5 on 2022-07-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_experience_image_alter_projects_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Involvements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='website/static/images')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('website_link', models.URLField(max_length=300)),
            ],
        ),
    ]
