# Generated by Django 4.0.5 on 2022-07-12 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_involvements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Involvements',
            new_name='Involvement',
        ),
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
