# Generated by Django 4.0.5 on 2022-07-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_involvements_involvement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='github_link',
        ),
        migrations.AddField(
            model_name='experience',
            name='position',
            field=models.CharField(default='', max_length=150),
        ),
    ]
