# Generated by Django 4.0.5 on 2022-07-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_experience_github_link_experience_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='timeline',
            field=models.CharField(default='', max_length=50),
        ),
    ]
