# Generated by Django 4.0.5 on 2022-07-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_experience_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='involvement',
            name='position',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='involvement',
            name='timeline',
            field=models.CharField(default='', max_length=50),
        ),
    ]
