# Generated by Django 4.0.5 on 2022-07-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_involvement_position_involvement_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='involvement',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
