# Generated by Django 4.0.5 on 2022-07-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_experience_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='involvement',
            name='description',
        ),
        migrations.AddField(
            model_name='involvement',
            name='description_one',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='involvement',
            name='description_two',
            field=models.CharField(default='', max_length=500),
        ),
    ]
