# Generated by Django 4.1 on 2022-08-31 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_remove_involvement_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Involvement',
        ),
    ]
